import { Injectable } from '@angular/core';
import JSZip from 'jszip';
import { Bundle, BundleMetadata } from '../models/bundle.model';

@Injectable({
  providedIn: 'root'
})
export class BundleService {

  async createAndDownloadBundle(bundle: Bundle): Promise<void> {
    const zip = new JSZip();
    
    // Add script.json
    zip.file('script.json', JSON.stringify({
      hook: bundle.script.hook,
      flow: bundle.script.flow,
      punchline: bundle.script.punchline,
      onScreenText: bundle.script.onScreenText,
      personaNotes: bundle.script.personaNotes,
      emotionalDirection: bundle.script.emotionalDirection
    }, null, 2));
    
    // Add storyboard images
    bundle.storyboardImages.forEach((imageDataUrl, index) => {
      const base64Data = imageDataUrl.split(',')[1];
      zip.file(`scene${index + 1}.png`, base64Data, { base64: true });
    });
    
    // Add music prompt
    zip.file('music-prompt.json', JSON.stringify(bundle.musicPrompt, null, 2));
    
    // Add props if any
    bundle.props.forEach((propDataUrl, index) => {
      const base64Data = propDataUrl.split(',')[1];
      zip.file(`prop${index + 1}.png`, base64Data, { base64: true });
    });
    
    // Add metadata
    zip.file('metadata.json', JSON.stringify(bundle.metadata, null, 2));
    
    // Add README
    const readme = this.generateReadme(bundle.metadata);
    zip.file('README.md', readme);
    
    // Generate ZIP and download
    const blob = await zip.generateAsync({ type: 'blob' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `visionaryclones-${Date.now()}.zip`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }

  private generateReadme(metadata: BundleMetadata): string {
    return `# VisionaryClones Bundle

Generated: ${new Date(metadata.generatedAt).toLocaleString()}
Version: ${metadata.version}

## Contents

- **script.json** - 24-second script with hook, flow, and punchline
- **scene1.png, scene2.png, scene3.png** - Storyboard images (9:16 portrait)
- **music-prompt.json** - Detailed music generation prompt
- **prop*.png** - Optional prop images (if uploaded)
- **metadata.json** - Generation metadata

## Metadata

- **Persona:** ${metadata.persona}
- **Topic:** ${metadata.topic}
- **Music Genre:** ${metadata.musicGenre}
- **Music Mood:** ${metadata.musicMood}

## Next Steps

1. Use the music prompt in **music-prompt.json** with a music generation tool (e.g., Suno, Udio, or MusicFX)
2. Import the storyboard images into your video editor (CapCut, Veo3, etc.)
3. Add the script as captions/voiceover
4. Sync with the generated music
5. Export and share!

---

Generated by VisionaryClones
https://vclones.web.app
`;
  }
}
