import { Injectable } from '@angular/core';
import JSZip from 'jszip';
import { Bundle, BundleMetadata } from '../models/bundle.model';

@Injectable({
  providedIn: 'root'
})
export class BundleService {

  async createAndDownloadBundle(bundle: Bundle): Promise<void> {
    const zip = new JSZip();
    
    // Add script.json at root
    zip.file('script.json', JSON.stringify(bundle.script, null, 2));
    
    // Create storyboard folder
    const storyboardFolder = zip.folder('storyboard');
    bundle.storyboardImages.forEach((imageDataUrl, index) => {
      const base64Data = imageDataUrl.split(',')[1];
      storyboardFolder!.file(`scene${index + 1}.png`, base64Data, { base64: true });
    });
    
    // Create music folder
    const musicFolder = zip.folder('music');
    musicFolder!.file('music-prompt.json', JSON.stringify(bundle.musicPrompt, null, 2));
    
    // Create props folder if props exist
    if (bundle.props.length > 0) {
      const propsFolder = zip.folder('props');
      bundle.props.forEach((propDataUrl, index) => {
        const base64Data = propDataUrl.split(',')[1];
        propsFolder!.file(`prop${index + 1}.png`, base64Data, { base64: true });
      });
    }
    
    // Add metadata.json at root
    zip.file('metadata.json', JSON.stringify(bundle.metadata, null, 2));
    
    // Add README.md
    const readme = this.generateReadme(bundle.metadata);
    zip.file('README.md', readme);
    
    // Generate ZIP and download
    const blob = await zip.generateAsync({ type: 'blob' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `visionaryclones-${Date.now()}.zip`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }

  private generateReadme(metadata: any): string {
    // Handle both v1.0 (BundleMetadata) and v1.1 (MetadataModel) formats
    const timestamp = metadata.timestamp || Date.parse(metadata.generatedAt);
    const persona = metadata.persona;
    const topic = metadata.topic;
    const imageModel = metadata.image_model_used || 'Imagen 4';
    const propsCount = metadata.props_count || 0;
    
    return `# VisionaryClones Bundle

Generated: ${new Date(timestamp).toLocaleString()}
Version: ${metadata.version || metadata.music_prompt_version || 'v1.1'}

## Contents

### Root Files
- **script.json** - 24-second script with hook, flow, and punchline
- **metadata.json** - Generation metadata

### Folders
- **storyboard/** - 3 storyboard images (9:16 portrait)
  - scene1.png
  - scene2.png
  - scene3.png
- **music/** - Music generation prompt
  - music-prompt.json
${propsCount > 0 ? `- **props/** - ${propsCount} prop image(s)\n` : ''}

## Metadata

- **Persona:** ${persona}
- **Topic:** ${topic}
- **Image Model:** ${imageModel}
${metadata.musicGenre ? `- **Music Genre:** ${metadata.musicGenre}\n- **Music Mood:** ${metadata.musicMood}` : ''}

## Next Steps

1. Use the music prompt in **music/music-prompt.json** with a music generation tool (e.g., Suno, Udio, or MusicFX)
2. Import the storyboard images from **storyboard/** into your video editor (CapCut, Veo3, etc.)
3. Add the script as captions/voiceover
4. Sync with the generated music
5. Export and share!

---

Generated by VisionaryClones v1.1
https://vclones.web.app
`;
  }
}
